Repository HYF-Class20/home, pull requests merged in 2023-04, with the labels that each got.

#62 Added saidakf.md bio to Home repo
  student-bios/andreia-negreira.md
  student-bios/saidakf.md
Labels: md

#77 Add Nana bio file
  student-bios/Nana99999.md
  student-bios/saidakf.md
Labels: md

#93 Update learners list and readme
  README.md
  admin/assets/avatars/HidayetKanpolat.png
  admin/learners.yml
Labels: documentation

#102 add sarah bio
  student-bios/SarahNaji12.md
Labels: week-1, md, individual, deliverable

#103 Update learners list and readme
  README.md
  admin/assets/avatars/C-Starry.png
  admin/assets/avatars/HidayetKanpolat.png
  admin/assets/avatars/Mouhamed-Alshlash.png
  admin/assets/avatars/tesfatsi.png
  admin/learners.yml
Labels: documentation

#100 Andy student's bio
  student-bios/andy-keshishian.md
  student-bios/img/KESHISHIANANDY.jpg
Labels: student-bio, md

#107 rename andy's md file
  student-bios/andykeshishian.md
Labels: enhancement, md

#109 edit img file name
  student-bios/andykeshishian.md
Labels: enhancement, md

#118 Update learners and readme
  README.md
  admin/assets/avatars/GabriellaLohy.png
  admin/assets/avatars/Gopiben.png
  admin/learners.yml
Labels: documentation

#121 add takang.md
  student-bios/takang03.md
Labels: student-bio, md

#122 Rename takang03.md to Takang03.md
  student-bios/Takang03.md
Labels: bug

#123 updated Osei-b4.md
  student-bios/Osei-b4.md
Labels: student-bio, md
