Repository HYF-Class20/home, pull requests merged in 2023-03, with the labels that each got.

#9 Adding Gabriella Bio
  student-bios/GabriellaLohy.md
Labels: week-1, check-in

#11 Adding Gabriella Bio
  student-bios/GabriellaLohy.md
Labels: week-1, check-in

#15 Delete .DS_Store
  .DS_Store
  .gitignore
Labels: bug

#18 Student-bio
  .DS_Store
  .gitignore
  student-bios/GabriellaLohy.md
Labels: check-in

#24 add ibrahim86ali.md
  student-bios/ibrahim86ali.md
Labels: week-2, individual

#23 Herbert Homolka's Student Bio
  .cspell.json
  chill-zone/README.md
  modules/lib/js-yaml.js
  package-lock.json
  student-bios/HerbertHomolka1.md
Labels: week-1, student-bio, individual

#7 my info and picture
  student-bios/GabriellaLohy.md
  student-bios/emran-ai.md
  student-bios/image/pic.JPG
Labels: md

#29 restore student-bios/GabriellaLohy.md
  student-bios/GabriellaLohy.md
Labels: bug

#54 Andreia negreira
  student-bios/andreia-negreira.md
Labels: week-1, md, individual, deliverable
